import { Button } from "std-widgets.slint";
import { Theme, AppI18n } from "../../theme.slint";

export component CheckUpdateDialog inherits Rectangle {
    in property <string> message_content: "";
    in property <bool> is_expire: false;
    in property <bool> show_cancel: true;
    callback download;
    callback close;
    background: #00000080;
    TouchArea { }

    Rectangle {
        width: 400px;
        height: 200px;
        background: Theme.card_bg;
        border-radius: 8px;
        border-width: 1px;
        border-color: Theme.border_color;
        drop-shadow-blur: 16px;
        drop-shadow-color: #00000040;
        VerticalLayout {
            padding: 24px;
            spacing: 16px;
            Text {
                text: root.is_expire ? AppI18n.t("dialog.expire_title", [AppI18n.version]) : AppI18n.t("dialog.update_check_title", [AppI18n.version]);
                font-size: 18px;
                font-weight: 500;
                color: Theme.text_primary;
            }

            VerticalLayout {
                spacing: 8px;
                Text {
                    text: message_content;
                    font-size: 14px;
                    color: Theme.text_primary;
                    wrap: word-wrap;
                }

                Text {
                    text: AppI18n.t("dialog.update_check_info", [AppI18n.version]);
                    font-size: 13px;
                    color: Theme.text_secondary;
                    wrap: word-wrap;
                }
            }

            Rectangle {
                vertical-stretch: 1;
            }

            HorizontalLayout {
                alignment: end;
                spacing: 12px;
                if (show_cancel): Button {
                    text: AppI18n.t("dialog.download_later", [AppI18n.version]);
                    height: 32px;
                    clicked => {
                        root.close();
                    }
                }
                Button {
                    text: AppI18n.t("dialog.download_now", [AppI18n.version]);
                    height: 32px;
                    primary: true;
                    clicked => {
                        root.download();
                    }
                }
            }
        }
    }
}
