import { Button } from "std-widgets.slint";
import { Theme, AppI18n } from "../../theme.slint";

export component MessageDialog inherits Rectangle {
    in property <string> message;
    callback close;
    background: #00000080;
    TouchArea { }

    Rectangle {
        width: 350px;
        height: 180px;
        background: Theme.card_bg;
        border-radius: 8px;
        border-width: 1px;
        border-color: Theme.border_color;
        drop-shadow-blur: 16px;
        drop-shadow-color: #00000040;
        VerticalLayout {
            padding: 24px;
            spacing: 16px;
            alignment: space-between;
            Text {
                text: AppI18n.t("dialog.info", [AppI18n.version]);
                font-size: 16px;
                font-weight: 600;
                color: Theme.text_primary;
            }

            Text {
                text: message;
                font-size: 14px;
                color: Theme.text_primary;
                wrap: word-wrap;
                horizontal-alignment: center;
                vertical-alignment: center;
                height: 48px;
            }

            HorizontalLayout {
                alignment: center;
                Button {
                    text: AppI18n.t("dialog.confirm", [AppI18n.version]);
                    height: 32px;
                    width: 100px;
                    clicked => {
                        root.close();
                    }
                }
            }
        }
    }
}
