import { Button } from "std-widgets.slint";
import { Theme, AppI18n } from "../../theme.slint";

export component StoreInstallWarnDialog inherits Rectangle {
    callback confirm;
    callback cancel;
    background: #00000080;
    TouchArea { }

    Rectangle {
        width: 420px;
        height: 200px;
        background: Theme.card_bg;
        border-radius: 8px;
        border-width: 1px;
        border-color: Theme.border_color;
        drop-shadow-blur: 16px;
        drop-shadow-color: #00000040;
        VerticalLayout {
            padding: 24px;
            spacing: 16px;
            Text {
                text: AppI18n.t("dialog.store_warn_title", [AppI18n.version]);
                font-size: 18px;
                font-weight: 500;
                color: Theme.text_primary;
            }

            Text {
                text: AppI18n.t("dialog.store_warn_msg", [AppI18n.version]);
                font-size: 14px;
                color: Theme.text_primary;
                wrap: word-wrap;
            }

            Rectangle {
                vertical-stretch: 1;
            }

            HorizontalLayout {
                alignment: end;
                spacing: 12px;
                Button {
                    text: AppI18n.t("dialog.store_exit", [AppI18n.version]);
                    height: 32px;
                    clicked => {
                        root.cancel();
                    }
                }

                Button {
                    text: AppI18n.t("dialog.store_continue", [AppI18n.version]);
                    height: 32px;
                    primary: true;
                    clicked => {
                        root.confirm();
                    }
                }
            }
        }
    }
}
