import { Theme, AppI18n, LayoutConstants } from "../../theme.slint";
import { CustomButton } from "../form_widgets.slint";

export component StoreInstallWarnDialog inherits Rectangle {
    callback confirm;
    callback cancel;
    background: #00000080;
    TouchArea { }

    Rectangle {
        width: 420px;
        height: 200px;
        background: Theme.card_bg;
        border-radius: 8px;
        border-width: 1px;
        border-color: Theme.border_color;
        drop-shadow-blur: 16px;
        drop-shadow-color: #00000040;
        VerticalLayout {
            padding: 24px;
            spacing: 16px;
            Text {
                text: AppI18n.t("dialog.store_warn_title", [AppI18n.version]);
                font-size: 18px * LayoutConstants.font-scale;
                font-family: Theme.default_font;
                font-weight: 500;
                color: Theme.text_primary;
                horizontal-alignment: AppI18n.is-rtl ? right : left;
            }

            Text {
                text: AppI18n.t("dialog.store_warn_msg", [AppI18n.version]);
                font-size: 14px * LayoutConstants.font-scale;
                font-family: Theme.default_font;
                color: Theme.text_primary;
                wrap: word-wrap;
                horizontal-alignment: AppI18n.is-rtl ? right : left;
            }

            Rectangle {
                vertical-stretch: 1;
            }

            HorizontalLayout {
                alignment: AppI18n.is-rtl ? start : end;
                spacing: 12px;
                if (AppI18n.is-rtl): CustomButton {
                    text: AppI18n.t("dialog.store_continue", [AppI18n.version]);
                    height: 32px;
                    primary: true;
                    clicked => {
                        root.confirm();
                    }
                }
                CustomButton {
                    text: AppI18n.t("dialog.store_exit", [AppI18n.version]);
                    height: 32px;
                    clicked => {
                        root.cancel();
                    }
                }

                if (!AppI18n.is-rtl): CustomButton {
                    text: AppI18n.t("dialog.store_continue", [AppI18n.version]);
                    height: 32px;
                    primary: true;
                    clicked => {
                        root.confirm();
                    }
                }
            }
        }
    }
}
